puts "The students of Villans Academy"
puts "------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Freddy Krueger"
puts "The Joker"
puts "Norman Bates"

print "Overall, we have "
print 11
puts " great students"
